server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.8e52674084d36c57
            clientSecret: 737e8f6fb3772ded004206937066e20abb89b45f
          google:
            clientId: 910840806347-2s0svi5i5l76fmkksuodaqjt3eiicuoo.apps.googleusercontent.com
            clientSecret: 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
  datasource:
#    url: jdbc:postgresql://postgres:5432/mvc # in case of deployment on the docker
    url: jdbc:postgresql://localhost:5332/mvc #sid or servicename
    username: yousef
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    database : postgresql
    database-platform : org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: test
#      password: test

