server:
  port: 8082

spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/mvc # in case of deployment on the docker
    url: jdbc:postgresql://localhost:5332/mvc #sid or servicename
    username: yousef
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    database : postgresql
    database-platform : org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: test
#      password: test

